# Generated by Django 5.0.4 on 2025-12-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilmReview',
            fields=[
                ('film_review_id', models.IntegerField(primary_key=True, serialize=False)),
                ('star_review', models.CharField(blank=True, max_length=45, null=True)),
                ('title_review', models.TextField(blank=True, null=True)),
                ('name_review', models.CharField(blank=True, max_length=45, null=True)),
                ('date_review', models.CharField(blank=True, max_length=45, null=True)),
                ('content_review', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Film Review',
                'verbose_name_plural': 'Film Reviews',
                'db_table': 'film_review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RatingFilm',
            fields=[
                ('rating_id', models.IntegerField(primary_key=True, serialize=False)),
                ('number_of_stars', models.CharField(blank=True, max_length=45, null=True)),
                ('percent_people_vote', models.CharField(blank=True, max_length=45, null=True)),
                ('number_people_vote', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'Rating Film',
                'verbose_name_plural': 'Rating Films',
                'db_table': 'rating',
                'managed': False,
            },
        ),
    ]
