# Generated by Django 5.0.4 on 2025-12-26 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeMovie',
            fields=[
                ('user_name', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Like Movie',
                'verbose_name_plural': 'Like Movies',
                'db_table': 'like_movie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FollowFilmUser',
            fields=[
                ('follow_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_view', models.IntegerField(default=0)),
                ('aggregate_rating', models.IntegerField(default=0, help_text='Aggregate rating from user activities (max rating from all activities)')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movieinformation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Follow Film User',
                'verbose_name_plural': 'Follow Film Users',
                'db_table': 'follow_film_user',
                'unique_together': {('movie', 'user')},
            },
        ),
    ]
