# Generated by Django 5.0.4 on 2025-12-26 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
    ]
