# Generated by Django 5.0.4 on 2024-06-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Film_BE', '0004_rename_movie_id_followfilmuser_movie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkImg',
            fields=[
                ('link_img_id', models.IntegerField(primary_key=True, serialize=False)),
                ('link_img', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'link_img',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LinkTrailer',
            fields=[
                ('link_trailer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('link_trailer', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'link_trailler',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'movie_img',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieTrailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'movie_trailler',
                'managed': False,
            },
        ),
    ]
