# Generated by Django 5.0.4 on 2024-06-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Film_BE', '0005_linkimg_linktrailer_movieimg_movietrailer'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'like_movie',
                'managed': False,
            },
        ),
    ]
