# Generated by Django 5.0.4 on 2025-12-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AspectRatio',
            fields=[
                ('aspect_ratio_id', models.IntegerField(primary_key=True, serialize=False)),
                ('aspect_ratio_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Aspect Ratio',
                'verbose_name_plural': 'Aspect Ratios',
                'db_table': 'aspect_ratio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('awards_id', models.IntegerField(primary_key=True, serialize=False)),
                ('awards_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Award',
                'verbose_name_plural': 'Awards',
                'db_table': 'awards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('camera_id', models.IntegerField(primary_key=True, serialize=False)),
                ('camera_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Camera',
                'verbose_name_plural': 'Cameras',
                'db_table': 'camera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('cast_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('role', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Cast',
                'verbose_name_plural': 'Casts',
                'db_table': 'cast',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CinematographicProcess',
            fields=[
                ('cinematographic_process_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cinematographic_process_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Cinematographic Process',
                'verbose_name_plural': 'Cinematographic Processes',
                'db_table': 'cinematographic_process',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cinematography',
            fields=[
                ('cinematography_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('role', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Cinematography',
                'verbose_name_plural': 'Cinematographies',
                'db_table': 'cinematography',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_id', models.IntegerField(primary_key=True, serialize=False)),
                ('color_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
                'db_table': 'color',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CountryOrigin',
            fields=[
                ('country_origin_id', models.IntegerField(primary_key=True, serialize=False)),
                ('country_origin_name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'Country Origin',
                'verbose_name_plural': 'Country Origins',
                'db_table': 'country_origin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DidYouKnow',
            fields=[
                ('did_you_know_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Did You Know',
                'verbose_name_plural': 'Did You Knows',
                'db_table': 'did_you_know',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('director_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('role', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Directors',
                'db_table': 'director',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Editing',
            fields=[
                ('editing_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('role', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Editing',
                'verbose_name_plural': 'Editings',
                'db_table': 'editing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FilmingLocations',
            fields=[
                ('filming_locations_id', models.IntegerField(primary_key=True, serialize=False)),
                ('filming_locations_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Filming Location',
                'verbose_name_plural': 'Filming Locations',
                'db_table': 'filming_locations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('genres_id', models.IntegerField(primary_key=True, serialize=False)),
                ('genres_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'db_table': 'genres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('laboratory_id', models.IntegerField(primary_key=True, serialize=False)),
                ('laboratory_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Laboratory',
                'verbose_name_plural': 'Laboratories',
                'db_table': 'laboratory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language_id', models.IntegerField(primary_key=True, serialize=False)),
                ('language_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'db_table': 'language',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LinkImg',
            fields=[
                ('link_img_id', models.IntegerField(primary_key=True, serialize=False)),
                ('link_img', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Link Image',
                'verbose_name_plural': 'Link Images',
                'db_table': 'link_img',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LinkTrailer',
            fields=[
                ('link_trailler_id', models.IntegerField(primary_key=True, serialize=False)),
                ('link_trailler', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Link Trailer',
                'verbose_name_plural': 'Link Trailers',
                'db_table': 'link_trailler',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'movie_cast',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieCinematography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'movie_cinematography',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'movie_director',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieEditing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'movie_editing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieGenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'movie_genres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'movie_img',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movieinformation',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=200)),
                ('original_name_movie', models.CharField(blank=True, max_length=200, null=True)),
                ('year_manufacture', models.CharField(blank=True, max_length=45, null=True)),
                ('release_date', models.CharField(blank=True, max_length=45, null=True)),
                ('time', models.CharField(blank=True, max_length=45, null=True)),
                ('link_img', models.TextField(blank=True, null=True)),
                ('link_trailer', models.TextField(blank=True, null=True)),
                ('describe_movie', models.TextField(blank=True, null=True)),
                ('storyline', models.TextField(blank=True, null=True)),
                ('rating', models.CharField(blank=True, max_length=45, null=True)),
                ('total_vote', models.CharField(blank=True, max_length=45, null=True)),
                ('main_img', models.TextField(blank=True, null=True)),
                ('main_trailer', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'db_table': 'movieinformation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'movie_music',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieProduced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'movie_produced',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieSpecialeffects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'movie_specialeffects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieTaglines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'movie_taglines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieTrailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'movie_trailler',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieWriters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'movie_writers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('music_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('role', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Music',
                'verbose_name_plural': 'Musics',
                'db_table': 'music',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NegativeFormat',
            fields=[
                ('negative_format_id', models.IntegerField(primary_key=True, serialize=False)),
                ('negative_format_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Negative Format',
                'verbose_name_plural': 'Negative Formats',
                'db_table': 'negative_format',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfficialSite',
            fields=[
                ('official_site_id', models.IntegerField(primary_key=True, serialize=False)),
                ('official_site_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Official Site',
                'verbose_name_plural': 'Official Sites',
                'db_table': 'official_site',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrintedFilmFormat',
            fields=[
                ('printed_film_format_id', models.IntegerField(primary_key=True, serialize=False)),
                ('printed_film_format_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Printed Film Format',
                'verbose_name_plural': 'Printed Film Formats',
                'db_table': 'printed_film_format',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produced',
            fields=[
                ('produced_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('role', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Produced',
                'verbose_name_plural': 'Produceds',
                'db_table': 'produced',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductionCompanies',
            fields=[
                ('production_companies_id', models.IntegerField(primary_key=True, serialize=False)),
                ('production_companies_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Production Company',
                'verbose_name_plural': 'Production Companies',
                'db_table': 'production_companies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SoundMix',
            fields=[
                ('sound_mix_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sound_mix_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Sound Mix',
                'verbose_name_plural': 'Sound Mixes',
                'db_table': 'sound_mix',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Specialeffects',
            fields=[
                ('special_effect_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('role', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Special Effect',
                'verbose_name_plural': 'Special Effects',
                'db_table': 'specialeffects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Taglines',
            fields=[
                ('taglines_id', models.IntegerField(primary_key=True, serialize=False)),
                ('taglines_content', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tagline',
                'verbose_name_plural': 'Taglines',
                'db_table': 'taglines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketRoom',
            fields=[
                ('ticket_room_id', models.IntegerField(primary_key=True, serialize=False)),
                ('budget', models.CharField(blank=True, max_length=45, null=True)),
                ('gross', models.CharField(blank=True, max_length=45, null=True)),
                ('opening_weekend', models.CharField(blank=True, max_length=45, null=True)),
                ('gross_worldwide', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'Ticket Room',
                'verbose_name_plural': 'Ticket Rooms',
                'db_table': 'ticket_room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Writers',
            fields=[
                ('writers_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('role', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Writer',
                'verbose_name_plural': 'Writers',
                'db_table': 'writers',
                'managed': False,
            },
        ),
    ]
