name: Update data and Update model

on: 
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: '0 0 * * *' # This cron expression runs the job daily
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          ref: main

      - name: Setup Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.11
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip 
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run update
        run: python ./Crawl/autoUpdate/crawl_json.py

      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: update.sql
          path: ./Crawl/autoUpdate/update.sql

      - name: Commit and push the update.sql file
        env: 
          GH_UPDATE: ${{ secrets.GH_UPDATE }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Update update.sql file'
          git push https://x-access-token:${{ secrets.GH_UPDATE }}@github.com/QuanTH02/movie-management-system.git main
        continue-on-error: true
